import * as dotenv from 'dotenv';
dotenv.config();

export const mbssLocator = {

        // Локаторы  в виджете
        'Виджет MBSS': '//*[@id="main-view"]',
        'Сворачивание виджета': '//*[@id="collapse-view-btn"]',
        'Возобновить чат': '//*[@id="bottom-action-btn"]',      
        'Аватар оператора': '//*[@id="avatar-manager"]',
        'Каунтер': '//*[@id="text-message-counter"]',
        'Имя оператора': '//*[@id="action-bar-heading"]',
        'Прикрепить': '//*[@id="attach-btn"]',
        "Запрос звонка": '//*[@id="call-btn-in-action-bar"]',
        "Запросить":  '//*[@id="request-btn-in-action-bar"]',
        "Отменить запрос": '//*[@id="cancel-call-btn-in-action-bar"]',
        "Закрыть форму загрузки": '//*[@id="close-button-for-attach-files"]',
        "Загрузить еще": '//*[@id="load-more-button-for-attach-files"]',
        "Отправить с дополнениями": '//*[@id="send-button-for-attach-files"]',
        "Поле ввода сообщения в форме загрузки": '//*[@id="input-for-attach-files"]',
        "Далее в пре-форме": '//div[@id="bottom-action-btn" and .//span[text()="Далее"]]',
        "Начать чат": '//div[@id="bottom-action-btn" and .//span[text()="Начать чат"]]',
        'Заголовок-заглушка хедера': '//*[@id="action-bar-heading"]',
        'Аватар-заглушка хедера': '//*[@id="avatar-manager"]',
        'Отправку сообщения в виджете': '//*[@id="send-message-btn"]',
        'Поле ввода сообщения в виджете': '//*[@id="message-text-input"]',
        'Закрыть комнату в виджете': '//*[@id="close-chat-btn"]',
        'Кнопка подтверждения в виджете': '//*[@id="close-confirmation-btn"]',
        
        "Test SOL":'//*[text()= "Test SOL"]',
        "Test FRESH":'//*[text()= "Test FRESH"]',
        "Test JET":'//*[text()= "Test JET"]',
        "Test IZZI":'//*[text()= "Test IZZI"]',
        "Test STARDA":'//*[text()= "Test STARDA"]',
        "Test DRIP":'//*[text()= "Test DRIP"]',
        "Test LEX":'//*[text()= "Test LEX"]',
        "Test MONRO":'//*[text()= "Test MONRO"]',
        "Test IRWIN":'//*[text()= "Test IRWIN"]',
        "Test 1GO":'//*[text()= "Test 1GO"]',
        "Test GIZBO":'//*[text()= "Test GIZBO"]',
        "Test FLAGMAN":'//*[text()= "Test FLAGMAN"]',
        "Test MARTIN":'//*[text()= "Test MARTIN"]',
        "Test ROX":'//*[text()= "Test ROX"]',
        "Test VOLNA":'//*[text()= "Test VOLNA"]',
        "Test LEGZO":'//*[text()= "Test LEGZO"]',
        "Test NIKA":'//*[text()= "Test NIKA"]',

        "Системное оператор общается LEGZO": `//*[text()= "С вами общается legzo_operator"]`,
        "Системное оператор общается SOL": `//*[text()= "С вами общается sol_operator"]`,
        "Системное оператор общается FRESH": `//*[text()= "С вами общается fresh_operator"]`,
        "Системное оператор общается JET": `//*[text()= "С вами общается jet_operator"]`,
        "Системное оператор общается IZZI": `//*[text()= "С вами общается izzi_operator"]`,
        "Системное оператор общается STARDA": `//*[text()= "С вами общается starda_operator"]`,
        "Системное оператор общается DRIP": `//*[text()= "С вами общается drip_operator"]`,
        "Системное оператор общается LEX": `//*[text()= "С вами общается lex_operator"]`,
        "Системное оператор общается MONRO": `//*[text()= "С вами общается monro_operator"]`,
        "Системное оператор общается IRWIN": `//*[text()= "С вами общается irwin_operator"]`,
        "Системное оператор общается 1GO": `//*[text()= "С вами общается 1go_operator"]`,
        "Системное оператор общается GIZBO": `//*[text()= "С вами общается gizbo_operator"]`,
        "Системное оператор общается FLAGMAN": `//*[text()= "С вами общается flagman_operator"]`,
        "Системное оператор общается MARTIN": `//*[text()= "С вами общается martin_operator"]`,
        "Системное оператор общается ROX": `//*[text()= "С вами общается rox_operator"]`,
        "Системное оператор общается VOLNA": `//*[text()= "С вами общается volna_operator"]`,
        "Системное оператор общается NIKA": `//*[text()= "С вами общается nika_operator"]`,
        
        "Системное оператор завершил LEGZO": `//*[text()= "legzo_operator завершил чат"]`,
        "Системное оператор завершил SOL": `//*[text()= "sol_operator завершил чат"]`,
        "Системное оператор завершил FRESH": `//*[text()= "fresh_operator завершил чат"]`,
        "Системное оператор завершил JET": `//*[text()= "jet_operator завершил чат"]`,
        "Системное оператор завершил IZZI": `//*[text()= "izzi_operator завершил чат"]`,
        "Системное оператор завершил STARDA": `//*[text()= "starda_operator завершил чат"]`,
        "Системное оператор завершил DRIP": `//*[text()= "drip_operator завершил чат"]`,
        "Системное оператор завершил LEX": `//*[text()= "lex_operator завершил чат"]`,
        "Системное оператор завершил MONRO": `//*[text()= "monro_operator завершил чат"]`,
        "Системное оператор завершил IRWIN": `//*[text()= "irwin_operator завершил чат"]`,
        "Системное оператор завершил 1GO": `//*[text()= "1go_operator завершил чат"]`,
        "Системное оператор завершил GIZBO": `//*[text()= "gizbo_operator завершил чат"]`,
        "Системное оператор завершил FLAGMAN": `//*[text()= "flagman_operator завершил чат"]`,
        "Системное оператор завершил MARTIN": `//*[text()= "martin_operator завершил чат"]`,
        "Системное оператор завершил ROX": `//*[text()= "rox_operator завершил чат"]`,
        "Системное оператор завершил VOLNA": `//*[text()= "volna_operator завершил чат"]`,
        "Системное оператор завершил NIKA": `//*[text()= "nika_operator завершил чат"]`,

        //Локаторы пре-форм 
        //LEGZO
        "Обязательный вопрос пре-формы LEGZO DEV": '//*[@data-message-id="1266" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы LEGZO DEV": '//*[@data-message-id="1266_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы LEGZO DEV": '//*[@data-message-id="1266_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы LEGZO DEV": '//*[@data-message-id="1267" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы LEGZO DEV": '//*[@data-message-id="1267_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы LEGZO DEV": '//*[@data-message-id="1267_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы LEGZO STAGE": '//*[@data-message-id="38" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы LEGZO STAGE": '//*[@data-message-id="38_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы LEGZO STAGE": '//*[@data-message-id="38_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы LEGZO STAGE": '//*[@data-message-id="39" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы LEGZO STAGE": '//*[@data-message-id="39_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы LEGZO STAGE": '//*[@data-message-id="39_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы LEGZO MASTER": '//*[@data-message-id="305" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы LEGZO MASTER": '//*[@data-message-id="305_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы LEGZO MASTER": '//*[@data-message-id="305_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы LEGZO MASTER": '//*[@data-message-id="306" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы LEGZO MASTER": '//*[@data-message-id="306_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы LEGZO MASTER": '//*[@data-message-id="306_1" and .//span[text()="Ответ 4"]]',
        
        //FRESH
        "Обязательный вопрос пре-формы FRESH DEV": '//*[@data-message-id="1270" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы FRESH DEV": '//*[@data-message-id="1270_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы FRESH DEV": '//*[@data-message-id="1270_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы FRESH DEV": '//*[@data-message-id="1271" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы FRESH DEV": '//*[@data-message-id="1271_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы FRESH DEV": '//*[@data-message-id="1271_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы FRESH STAGE": '//*[@data-message-id="40" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы FRESH STAGE": '//*[@data-message-id="40_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы FRESH STAGE": '//*[@data-message-id="40_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы FRESH STAGE": '//*[@data-message-id="41" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы FRESH STAGE": '//*[@data-message-id="41_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы FRESH STAGE": '//*[@data-message-id="41_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы FRESH MASTER": '//*[@data-message-id="307" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы FRESH MASTER": '//*[@data-message-id="307_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы FRESH MASTER": '//*[@data-message-id="307_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы FRESH MASTER": '//*[@data-message-id="308" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы FRESH MASTER": '//*[@data-message-id="308_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы FRESH MASTER": '//*[@data-message-id="308_1" and .//span[text()="Ответ 4"]]',

        //ROX
        "Обязательный вопрос пре-формы ROX STAGE": '//*[@data-message-id="43" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы ROX STAGE": '//*[@data-message-id="43_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы ROX STAGE": '//*[@data-message-id="43_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы ROX STAGE": '//*[@data-message-id="44" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы ROX STAGE": '//*[@data-message-id="44_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы ROX STAGE": '//*[@data-message-id="44_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы ROX MASTER": '//*[@data-message-id="309" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы ROX MASTER": '//*[@data-message-id="309_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы ROX MASTER": '//*[@data-message-id="309_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы ROX MASTER": '//*[@data-message-id="310" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы ROX MASTER": '//*[@data-message-id="310_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы ROX MASTER": '//*[@data-message-id="310_1" and .//span[text()="Ответ 4"]]',
        
        //MARTIN
        "Обязательный вопрос пре-формы MARTIN STAGE": '//*[@data-message-id="45" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы MARTIN STAGE": '//*[@data-message-id="45_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы MARTIN STAGE": '//*[@data-message-id="45_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы MARTIN STAGE": '//*[@data-message-id="46" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы MARTIN STAGE": '//*[@data-message-id="46_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы MARTIN STAGE": '//*[@data-message-id="46_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы MARTIN MASTER": '//*[@data-message-id="311" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы MARTIN MASTER": '//*[@data-message-id="311_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы MARTIN MASTER": '//*[@data-message-id="311_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы MARTIN MASTER": '//*[@data-message-id="312" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы MARTIN MASTER": '//*[@data-message-id="312_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы MARTIN MASTER": '//*[@data-message-id="312_1" and .//span[text()="Ответ 4"]]',
        
        //DRIP
        "Обязательный вопрос пре-формы DRIP STAGE": '//*[@data-message-id="159" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы DRIP STAGE": '//*[@data-message-id="159_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы DRIP STAGE": '//*[@data-message-id="159_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы DRIP STAGE": '//*[@data-message-id="160" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы DRIP STAGE": '//*[@data-message-id="160_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы DRIP STAGE": '//*[@data-message-id="160_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы DRIP MASTER": '//*[@data-message-id="313" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы DRIP MASTER": '//*[@data-message-id="313_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы DRIP MASTER": '//*[@data-message-id="313_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы DRIP MASTER": '//*[@data-message-id="314" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы DRIP MASTER": '//*[@data-message-id="314_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы DRIP MASTER": '//*[@data-message-id="314_1" and .//span[text()="Ответ 4"]]',

        //SOL
        "Обязательный вопрос пре-формы SOL DEV": '//*[@data-message-id="1268" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы SOL DEV": '//*[@data-message-id="1268_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы SOL DEV": '//*[@data-message-id="1268_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы SOL DEV": '//*[@data-message-id="1269" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы SOL DEV": '//*[@data-message-id="1269_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы SOL DEV": '//*[@data-message-id="1269_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы SOL STAGE": '//*[@data-message-id="161" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы SOL STAGE": '//*[@data-message-id="161_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы SOL STAGE": '//*[@data-message-id="161_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы SOL STAGE": '//*[@data-message-id="162" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы SOL STAGE": '//*[@data-message-id="162_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы SOL STAGE": '//*[@data-message-id="162_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы SOL MASTER": '//*[@data-message-id="315" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы SOL MASTER": '//*[@data-message-id="315_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы SOL MASTER": '//*[@data-message-id="315_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы SOL MASTER": '//*[@data-message-id="316" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы SOL MASTER": '//*[@data-message-id="316_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы SOL MASTER": '//*[@data-message-id="316_1" and .//span[text()="Ответ 4"]]',

        //IZZI
        "Обязательный вопрос пре-формы IZZI STAGE": '//*[@data-message-id="163" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы IZZI STAGE": '//*[@data-message-id="163_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы IZZI STAGE": '//*[@data-message-id="163_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы IZZI STAGE": '//*[@data-message-id="164" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы IZZI STAGE": '//*[@data-message-id="164_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы IZZI STAGE": '//*[@data-message-id="164_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы IZZI MASTER": '//*[@data-message-id="317" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы IZZI MASTER": '//*[@data-message-id="317_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы IZZI MASTER": '//*[@data-message-id="317_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы IZZI MASTER": '//*[@data-message-id="318" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы IZZI MASTER": '//*[@data-message-id="318_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы IZZI MASTER": '//*[@data-message-id="318_1" and .//span[text()="Ответ 4"]]',

        //VOLNA
        "Обязательный вопрос пре-формы VOLNA STAGE": '//*[@data-message-id="167" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы VOLNA STAGE": '//*[@data-message-id="167_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы VOLNA STAGE": '//*[@data-message-id="167_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы VOLNA STAGE": '//*[@data-message-id="168" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы VOLNA STAGE": '//*[@data-message-id="168_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы VOLNA STAGE": '//*[@data-message-id="168_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы VOLNA MASTER": '//*[@data-message-id="319" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы VOLNA MASTER": '//*[@data-message-id="319_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы VOLNA MASTER": '//*[@data-message-id="319_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы VOLNA MASTER": '//*[@data-message-id="320" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы VOLNA MASTER": '//*[@data-message-id="320_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы VOLNA MASTER": '//*[@data-message-id="320_1" and .//span[text()="Ответ 4"]]',

        //STARDA
        "Обязательный вопрос пре-формы STARDA STAGE": '//*[@data-message-id="169" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы STARDA STAGE": '//*[@data-message-id="169_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы STARDA STAGE": '//*[@data-message-id="169_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы STARDA STAGE": '//*[@data-message-id="170" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы STARDA STAGE": '//*[@data-message-id="170_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы STARDA STAGE": '//*[@data-message-id="170_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы STARDA MASTER": '//*[@data-message-id="321" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы STARDA MASTER": '//*[@data-message-id="321_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы STARDA MASTER": '//*[@data-message-id="321_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы STARDA MASTER": '//*[@data-message-id="322" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы STARDA MASTER": '//*[@data-message-id="322_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы STARDA MASTER": '//*[@data-message-id="322_1" and .//span[text()="Ответ 4"]]',

        //MONRO
        "Обязательный вопрос пре-формы MONRO STAGE": '//*[@data-message-id="171" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы MONRO STAGE": '//*[@data-message-id="171_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы MONRO STAGE": '//*[@data-message-id="171_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы MONRO STAGE": '//*[@data-message-id="172" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы MONRO STAGE": '//*[@data-message-id="172_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы MONRO STAGE": '//*[@data-message-id="172_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы MONRO MASTER": '//*[@data-message-id="323" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы MONRO MASTER": '//*[@data-message-id="323_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы MONRO MASTER": '//*[@data-message-id="323_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы MONRO MASTER": '//*[@data-message-id="324" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы MONRO MASTER": '//*[@data-message-id="324_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы MONRO MASTER": '//*[@data-message-id="324_1" and .//span[text()="Ответ 4"]]',

        //1GO
        "Обязательный вопрос пре-формы 1GO STAGE": '//*[@data-message-id="173" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы 1GO STAGE": '//*[@data-message-id="173_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы 1GO STAGE": '//*[@data-message-id="173_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы 1GO STAGE": '//*[@data-message-id="174" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы 1GO STAGE": '//*[@data-message-id="174_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы 1GO STAGE": '//*[@data-message-id="174_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы 1GO MASTER": '//*[@data-message-id="325" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы 1GO MASTER": '//*[@data-message-id="325_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы 1GO MASTER": '//*[@data-message-id="325_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы 1GO MASTER": '//*[@data-message-id="326" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы 1GO MASTER": '//*[@data-message-id="326_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы 1GO MASTER": '//*[@data-message-id="326_1" and .//span[text()="Ответ 4"]]',

        //LEX
        "Обязательный вопрос пре-формы LEX STAGE": '//*[@data-message-id="175" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы LEX STAGE": '//*[@data-message-id="175_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы LEX STAGE": '//*[@data-message-id="175_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы LEX STAGE": '//*[@data-message-id="176" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы LEX STAGE": '//*[@data-message-id="176_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы LEX STAGE": '//*[@data-message-id="176_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы LEX MASTER": '//*[@data-message-id="327" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы LEX MASTER": '//*[@data-message-id="327_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы LEX MASTER": '//*[@data-message-id="327_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы LEX MASTER": '//*[@data-message-id="328" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы LEX MASTER": '//*[@data-message-id="328_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы LEX MASTER": '//*[@data-message-id="328_1" and .//span[text()="Ответ 4"]]',

        //GIZBO
        "Обязательный вопрос пре-формы GIZBO STAGE": '//*[@data-message-id="34" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы GIZBO STAGE": '//*[@data-message-id="34_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы GIZBO STAGE": '//*[@data-message-id="34_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы GIZBO STAGE": '//*[@data-message-id="177" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы GIZBO STAGE": '//*[@data-message-id="177_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы GIZBO STAGE": '//*[@data-message-id="177_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы GIZBO MASTER": '//*[@data-message-id="329" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы GIZBO MASTER": '//*[@data-message-id="329_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы GIZBO MASTER": '//*[@data-message-id="329_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы GIZBO MASTER": '//*[@data-message-id="330" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы GIZBO MASTER": '//*[@data-message-id="330_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы GIZBO MASTER": '//*[@data-message-id="330_1" and .//span[text()="Ответ 4"]]',

        //IRWIN
        "Обязательный вопрос пре-формы IRWIN STAGE": '//*[@data-message-id="178" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы IRWIN STAGE": '//*[@data-message-id="178_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы IRWIN STAGE": '//*[@data-message-id="178_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы IRWIN STAGE": '//*[@data-message-id="179" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы IRWIN STAGE": '//*[@data-message-id="179_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы IRWIN STAGE": '//*[@data-message-id="179_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы IRWIN MASTER": '//*[@data-message-id="335" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы IRWIN MASTER": '//*[@data-message-id="335_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы IRWIN MASTER": '//*[@data-message-id="335_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы IRWIN MASTER": '//*[@data-message-id="336" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы IRWIN MASTER": '//*[@data-message-id="336_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы IRWIN MASTER": '//*[@data-message-id="336_1" and .//span[text()="Ответ 4"]]',

        //FLAGMAN
        "Обязательный вопрос пре-формы FLAGMAN STAGE": '//*[@data-message-id="180" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы FLAGMAN STAGE": '//*[@data-message-id="180_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы FLAGMAN STAGE": '//*[@data-message-id="180_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы FLAGMAN STAGE": '//*[@data-message-id="181" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы FLAGMAN STAGE": '//*[@data-message-id="181_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы FLAGMAN STAGE": '//*[@data-message-id="181_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы FLAGMAN MASTER": '//*[@data-message-id="337" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы FLAGMAN MASTER": '//*[@data-message-id="337_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы FLAGMAN MASTER": '//*[@data-message-id="337_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы FLAGMAN MASTER": '//*[@data-message-id="338" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы FLAGMAN MASTER": '//*[@data-message-id="338_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы FLAGMAN MASTER": '//*[@data-message-id="338_1" and .//span[text()="Ответ 4"]]',
        
        //JET
        "Обязательный вопрос пре-формы JET DEV": '//*[@data-message-id="1272" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы JET DEV": '//*[@data-message-id="1272_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы JET DEV": '//*[@data-message-id="1272_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы JET DEV": '//*[@data-message-id="1273" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы JET DEV": '//*[@data-message-id="1273_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы JET DEV": '//*[@data-message-id="1273_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы JET STAGE": '//*[@data-message-id="165" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы JET STAGE": '//*[@data-message-id="165_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы JET STAGE": '//*[@data-message-id="165_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы JET STAGE": '//*[@data-message-id="166" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы JET STAGE": '//*[@data-message-id="166_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы JET STAGE": '//*[@data-message-id="166_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы JET MASTER": '//*[@data-message-id="339" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы JET MASTER": '//*[@data-message-id="339_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы JET MASTER": '//*[@data-message-id="339_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы JET MASTER": '//*[@data-message-id="340" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы JET MASTER": '//*[@data-message-id="340_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы JET MASTER": '//*[@data-message-id="340_1" and .//span[text()="Ответ 4"]]',

        //NIKA
        "Обязательный вопрос пре-формы NIKA MASTER": '//*[@data-message-id="1" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы NIKA MASTER": '//*[@data-message-id="1_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы NIKA MASTER": '//*[@data-message-id="1_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы NIKA MASTER": '//*[@data-message-id="2" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы NIKA MASTER": '//*[@data-message-id="2_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы NIKA MASTER": '//*[@data-message-id="2_1" and .//span[text()="Ответ 4"]]',
        "Обязательный вопрос пре-формы NIKA STAGE": '//*[@data-message-id="5" and .//span[text()="Обязательный вопрос"]]',
        "Ответ 1 обязательной пре-формы NIKA STAGE": '//*[@data-message-id="5_0" and .//span[text()="Ответ 1"]]',
        "Ответ 2 обязательной пре-формы NIKA STAGE": '//*[@data-message-id="5_1" and .//span[text()="Ответ 2"]]',
        "Не обязательный вопрос пре-формы NIKA STAGE": '//*[@data-message-id="6" and .//span[text()="Не обязательный вопрос"]]',
        "Ответ 1 не обязательной пре-формы NIKA STAGE": '//*[@data-message-id="6_0" and .//span[text()="Ответ 3"]]',
        "Ответ 2 не обязательной пре-формы NIKA STAGE": '//*[@data-message-id="6_1" and .//span[text()="Ответ 4"]]',



        // Функциональные локаторы 
        'Локатор': (text) => `//*[text() = "${text}"]`,
        'Спецсимвольное сообщение': (text) => `text=${text}`,
        'ЛокаторФайла': (fileName) => `//*[img and normalize-space(.)="${fileName}"]`,
        'Отправленное изображение': '//img[contains(@src, ".jpg")]', //Проверяю первый отображаемый локатор(так как может )

};











